// This file is auto-generated by drizzleloader. DO NOT EDIT.


export class DrizzleLoaderNotFound extends Error {
  readonly table: string;
  readonly columns: Record<string, unknown>[];

  constructor(options: { table: string; columns: Record<string, unknown>[] }) {
    const columnStr = options.columns
      .map((col) =>
        Object.entries(col)
          .map(([k, v]) => `${k}=${JSON.stringify(v)}`)
          .join(", "),
      )
      .join("; ");
    super(`Record not found in ${options.table} for ${columnStr}`);
    this.name = "DrizzleLoaderNotFound";
    this.table = options.table;
    this.columns = options.columns;
  }
}

export function buildLookupMap<K, V>(
  rows: V[],
  keyFn: (row: V) => K,
): Map<K, V> {
  return new Map(rows.map((row) => [keyFn(row), row]));
}

export function lookupOrError<K, V>(
  map: Map<K, V>,
  key: K,
  table: string,
  column: string,
): V | DrizzleLoaderNotFound {
  return (
    map.get(key) ??
    new DrizzleLoaderNotFound({ table, columns: [{ [column]: key }] })
  );
}
