// This file is auto-generated by drizzleloader. DO NOT EDIT.

import { createPostsLoaders } from "./drizzleloaders/posts.js";
import { type DrizzleDb } from "./drizzleloaders/_internal.js";

export { DrizzleLoaderNotFound } from "drizzleloader";

export function createDrizzleLoaders(db: DrizzleDb) {
  return {
    posts: createPostsLoaders(db),
  };
}
