// This file is auto-generated by drizzleloader. DO NOT EDIT.

import DataLoader from "dataloader";
import { inArray } from "drizzle-orm";
import type { InferSelectModel } from "drizzle-orm";
import {
  DrizzleLoaderNotFound,
  buildLookupMap,
  lookupOrError,
} from "./_runtime.js";
import * as __schema from "../schema.js";
import { type DrizzleDb } from "./_internal.js";

export function createUsersLoaders(db: DrizzleDb) {
  const byId = new DataLoader<number, InferSelectModel<typeof __schema.users>>(
    async (ids) => {
      const rows = await db.select().from(__schema.users).where(inArray(__schema.users.id, [...ids]));
      const map = buildLookupMap(rows, (row) => row.id);
      return ids.map((key) => lookupOrError(map, key, "users", "id"));
    }
  );
  const byEmail = new DataLoader<string, InferSelectModel<typeof __schema.users>>(
    async (emails) => {
      const rows = await db.select().from(__schema.users).where(inArray(__schema.users.email, [...emails]));
      const map = buildLookupMap(rows, (row) => row.email);
      return emails.map((key) => lookupOrError(map, key, "users", "email"));
    }
  );
  return { byId, byEmail };
}
