// This file is auto-generated by drizzleloader. DO NOT EDIT.
import DataLoader from "dataloader";
import { inArray } from "drizzle-orm";
import type { InferSelectModel } from "drizzle-orm";
import {
  DrizzleLoaderNotFound,
  buildLookupMap,
  lookupOrError,
  buildCompositeLookupMap,
  serializeCompositeKey,
  queryCompositeKey,
} from "drizzleloader";
import * as __schema from "../schema.js";
import { type DrizzleDb } from "./_internal.js";

export function createPostsLoaders(db: DrizzleDb) {
  const byId = new DataLoader<number, InferSelectModel<typeof __schema.posts>>(
    async (ids) => {
      const rows = await db.select().from(__schema.posts).where(inArray(__schema.posts.id, [...ids]));
      const map = buildLookupMap(rows, (row) => row.id);
      return ids.map((key) => lookupOrError(map, key, "posts", "id"));
    }
  );
  const byAuthorIdAndCategory = new DataLoader<{ authorId: number; category: string }, InferSelectModel<typeof __schema.posts>[], string>(
    async (keys) => {
      const rows = await queryCompositeKey(db, __schema.posts, [__schema.posts.authorId, __schema.posts.category], ["authorId", "category"], keys as readonly Record<string, unknown>[]);
      const map = buildCompositeLookupMap(rows, ["authorId", "category"] as const);
      return keys.map((key) => map.get(serializeCompositeKey(key, ["authorId", "category"] as const)) ?? []);
    },
    { cacheKeyFn: (key) => serializeCompositeKey(key, ["authorId", "category"] as const) }
  );
  return { byId, byAuthorIdAndCategory };
}
