// This file is auto-generated by drizzleloader. DO NOT EDIT.
import { createUserRolesLoaders } from "./drizzleloaders/userRoles.js";
import { type DrizzleDb } from "./drizzleloaders/_internal.js";

export { DrizzleLoaderNotFound } from "drizzleloader";

export function createDrizzleLoaders(db: DrizzleDb) {
  return {
    user_roles: createUserRolesLoaders(db),
  };
}
