// This file is auto-generated by drizzleloader. DO NOT EDIT.
import { createUsersLoaders } from "./drizzleloaders/users.js";
import { type DrizzleDb } from "./drizzleloaders/_runtime.js";

export { DrizzleLoaderNotFound } from "./drizzleloaders/_runtime.js";

export function createDrizzleLoaders(db: DrizzleDb) {
  return {
    users: createUsersLoaders(db),
  };
}
