// This file is auto-generated by drizzleloader. DO NOT EDIT.
import { createUsersLoaders } from "./drizzleloaders/users.js";
import { createPostsLoaders } from "./drizzleloaders/posts.js";
import { type DrizzleDb } from "./drizzleloaders/_internal.js";

export { DrizzleLoaderNotFound } from "drizzleloader";

export function createDrizzleLoaders(db: DrizzleDb) {
  return {
    users: createUsersLoaders(db),
    posts: createPostsLoaders(db),
  };
}
