// This file is auto-generated by drizzleloader. DO NOT EDIT.

import { createItemsLoaders } from "./drizzleloaders/items.js";
import { type DrizzleDb } from "./drizzleloaders/_internal.js";

export { DrizzleLoaderNotFound } from "./drizzleloaders/_runtime.js";

export function createDrizzleLoaders(db: DrizzleDb) {
  return {
    items: createItemsLoaders(db),
  };
}
